### ISSUE TITLE
No global recoveries?

### ISSUE THREAD

**Issue by ghost** [mazik/corona-tracker#4]
How can there be zero recoveries worldwide (displayed in the bottom of the popup window) when there are several local recoveries (displayed in the main pie diagram)?

**Comment by mmikhan** [comment]
A fix has already been submitted to Chrome Webstore. Once the fix is released in v1.2, you can see the total recoveries number.

**Comment by mmikhan** [comment]
V1.2 is now available in Chrome web store and that fixes the issue.
